import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { FIXTURES } from '@/lib/vision/fixtures';
import { decodePng } from '@/lib/vision/testing/decodePng';
import {
  decodeTemplates,
  encodeTemplates,
  TEMPLATE_SOURCES,
  templatesFromScreenshot,
} from '@/lib/vision/templates';
import { GENERATED_TEMPLATES } from '@/lib/vision/templates.generated';

const fixturePath = (file: string) => fileURLToPath(new URL(`./__fixtures__/${file}`, import.meta.url));

function buildFromSources(): string[] {
  return TEMPLATE_SOURCES.flatMap((file) => {
    const fixture = FIXTURES.find((f) => f.file === file);
    if (!fixture) throw new Error(`no fixture ${file}`);
    return encodeTemplates(templatesFromScreenshot(decodePng(fixturePath(file)), fixture.board));
  });
}

describe('templates', () => {
  // The shipped templates must be exactly what the current code cuts from the
  // source fixtures. After changing glyph extraction, regenerate with
  //   BUILD_TEMPLATES=1 npx vitest run lib/vision/templates.test.ts
  // (PowerShell: $env:BUILD_TEMPLATES='1'; npx vitest run lib/vision/templates.test.ts)
  it('templates.generated.ts is in sync with the source fixtures', () => {
    const built = buildFromSources();
    if (process.env.BUILD_TEMPLATES === '1') {
      const body = built.map((line) => `  '${line}',`).join('\n');
      writeFileSync(
        fileURLToPath(new URL('./templates.generated.ts', import.meta.url)),
        `// Generated by lib/vision/templates.test.ts from the TEMPLATE_SOURCES fixtures.\n` +
          `// Do not edit: run the tests with BUILD_TEMPLATES=1 to regenerate.\n` +
          `export const GENERATED_TEMPLATES: readonly string[] = [\n${body}\n];\n`,
      );
      return;
    }
    expect(GENERATED_TEMPLATES).toEqual(built);
  });

  it('round-trips through the serialised form (to 1/255 per pixel)', () => {
    const [first] = decodeTemplates(buildFromSources().slice(0, 1));
    const again = decodeTemplates(encodeTemplates([first]))[0];
    expect(again.value).toBe(first.value);
    expect(again.aspect).toBeCloseTo(first.aspect, 4);
    again.pixels.forEach((v, i) => expect(Math.abs(v - first.pixels[i])).toBeLessThanOrEqual(1 / 255));
  });
});
